INSERT INTO TBL_DISPATCH (DISPATCH_NO, VEHICLE_TYPE, LICENSE_PLATE, OPERATOR, EMP_NO, MODIFIER, CREATE_DATE, MODIFY_DATE, USE_YN)
VALUES (DISPATCH_NO_SEQ.NEXTVAL, '냉동윙', '12가 3456', '홍길동', 1003, 1003, SYSDATE, SYSDATE, 'Y');

INSERT INTO TBL_DISPATCH (DISPATCH_NO, VEHICLE_TYPE, LICENSE_PLATE, OPERATOR, EMP_NO, MODIFIER, CREATE_DATE, MODIFY_DATE, USE_YN)
VALUES (DISPATCH_NO_SEQ.NEXTVAL, '냉동탑', '34나 7890', '김철수', 1003, 1003, SYSDATE, SYSDATE, 'Y');

INSERT INTO TBL_DISPATCH (DISPATCH_NO, VEHICLE_TYPE, LICENSE_PLATE, OPERATOR, EMP_NO, MODIFIER, CREATE_DATE, MODIFY_DATE, USE_YN)
VALUES (DISPATCH_NO_SEQ.NEXTVAL, '냉장윙', '56다 1234', '이영희', 1003, 1003, SYSDATE, SYSDATE, 'Y');

INSERT INTO TBL_DISPATCH (DISPATCH_NO, VEHICLE_TYPE, LICENSE_PLATE, OPERATOR, EMP_NO, MODIFIER, CREATE_DATE, MODIFY_DATE, USE_YN)
VALUES (DISPATCH_NO_SEQ.NEXTVAL, '냉장탑', '78마 5678', '박민수', 1003, 1003, SYSDATE, SYSDATE, 'Y');

INSERT INTO TBL_DISPATCH (DISPATCH_NO, VEHICLE_TYPE, LICENSE_PLATE, OPERATOR, EMP_NO, MODIFIER, CREATE_DATE, MODIFY_DATE, USE_YN)
VALUES (DISPATCH_NO_SEQ.NEXTVAL, '탑', '90바 4321', '정수정', 1003, 1003, SYSDATE, SYSDATE, 'Y');

INSERT INTO TBL_DISPATCH (DISPATCH_NO, VEHICLE_TYPE, LICENSE_PLATE, OPERATOR, EMP_NO, MODIFIER, CREATE_DATE, MODIFY_DATE, USE_YN)
VALUES (DISPATCH_NO_SEQ.NEXTVAL, '냉동윙', '12가 6789', '최영준', 1003, 1003, SYSDATE, SYSDATE, 'Y');

INSERT INTO TBL_DISPATCH (DISPATCH_NO, VEHICLE_TYPE, LICENSE_PLATE, OPERATOR, EMP_NO, MODIFIER, CREATE_DATE, MODIFY_DATE, USE_YN)
VALUES (DISPATCH_NO_SEQ.NEXTVAL, '냉동탑', '34나 9876', '김미영', 1003, 1003, SYSDATE, SYSDATE, 'Y');

INSERT INTO TBL_DISPATCH (DISPATCH_NO, VEHICLE_TYPE, LICENSE_PLATE, OPERATOR, EMP_NO, MODIFIER, CREATE_DATE, MODIFY_DATE, USE_YN)
VALUES (DISPATCH_NO_SEQ.NEXTVAL, '냉장윙', '56다 3456', '한지훈', 1003, 1003, SYSDATE, SYSDATE, 'Y');

INSERT INTO TBL_DISPATCH (DISPATCH_NO, VEHICLE_TYPE, LICENSE_PLATE, OPERATOR, EMP_NO, MODIFIER, CREATE_DATE, MODIFY_DATE, USE_YN)
VALUES (DISPATCH_NO_SEQ.NEXTVAL, '냉장탑', '78마 7654', '임지민', 1003, 1003, SYSDATE, SYSDATE, 'Y');

INSERT INTO TBL_DISPATCH (DISPATCH_NO, VEHICLE_TYPE, LICENSE_PLATE, OPERATOR, EMP_NO, MODIFIER, CREATE_DATE, MODIFY_DATE, USE_YN)
VALUES (DISPATCH_NO_SEQ.NEXTVAL, '탑', '90바 8765', '오승현', 1003, 1003, SYSDATE, SYSDATE, 'Y');

COMMIT;