INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.1', '내용 입니다.1', SYSDATE, 258, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '인사', '제목입니다.2', '내용 입니다.2', SYSDATE, 145, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '총무', '제목입니다.3', '내용 입니다.3', SYSDATE, 412, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '영업', '제목입니다.4', '내용 입니다.4', SYSDATE, 389, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.5', '내용 입니다.5', SYSDATE, 305, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '인사', '제목입니다.6', '내용 입니다.6', SYSDATE, 89, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '총무', '제목입니다.7', '내용 입니다.7', SYSDATE, 450, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '영업', '제목입니다.8', '내용 입니다.8', SYSDATE, 342, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.9', '내용 입니다.9', SYSDATE, 167, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.10', '내용 입니다.10', SYSDATE, 210, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '인사', '제목입니다.11', '내용 입니다.11', SYSDATE, 68, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '총무', '제목입니다.12', '내용 입니다.12', SYSDATE, 276, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '영업', '제목입니다.13', '내용 입니다.13', SYSDATE, 68, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.14', '내용 입니다.14', SYSDATE, 93, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '전체', '제목입니다.15', '내용 입니다.15', SYSDATE, 102, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '전체', '제목입니다.16', '내용 입니다.16', SYSDATE, 410, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '전체', '제목입니다.17', '내용 입니다.17', SYSDATE, 121, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '전체', '제목입니다.18', '내용 입니다.18', SYSDATE, 122, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '전체', '제목입니다.19', '내용 입니다.19', SYSDATE, 238, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '전체', '제목입니다.20', '내용 입니다.20', SYSDATE, 341, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '전체', '제목입니다.21', '내용 입니다.21', SYSDATE, 295, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.22', '내용 입니다.22', SYSDATE, 147, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.23', '내용 입니다.23', SYSDATE, 190, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.24', '내용 입니다.24', SYSDATE, 106, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.25', '내용 입니다.25', SYSDATE, 26, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.26', '내용 입니다.26', SYSDATE, 91, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '인사', '제목입니다.27', '내용 입니다.27', SYSDATE, 395, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '총무', '제목입니다.28', '내용 입니다.28', SYSDATE, 17, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '영업', '제목입니다.29', '내용 입니다.29', SYSDATE, 489, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '전체', '제목입니다.30', '내용 입니다.30', SYSDATE, 153, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '인사', '제목입니다.31', '내용 입니다.31', SYSDATE, 66, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '총무', '제목입니다.32', '내용 입니다.32', SYSDATE, 113, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '영업', '제목입니다.33', '내용 입니다.33', SYSDATE, 324, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.34', '내용 입니다.34', SYSDATE, 49, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '전체', '제목입니다.35', '내용 입니다.35', SYSDATE, 111, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '인사', '제목입니다.36', '내용 입니다.36', SYSDATE, 425, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '총무', '제목입니다.37', '내용 입니다.37', SYSDATE, 370, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '영업', '제목입니다.38', '내용 입니다.38', SYSDATE, 148, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 2, '전체', '제목입니다.39', '내용 입니다.39', SYSDATE, 264, 1003, SYSDATE, NULL, NULL, 'Y');

INSERT INTO TBL_BOARD (
    BOARD_NO, BOARD_TYPE_NO, BOARD_DEPT, BOARD_TITLE, BOARD_CONTENT,
    REGIST_DATE, COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (BOARD_NO_SEQ.NEXTVAL, 1, '전체', '제목입니다.40', '내용 입니다.40', SYSDATE, 67, 1003, SYSDATE, NULL, NULL, 'Y');


--REPLY SAMPLE
INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '좋은 글 감사합니다', NULL, NULL, 'A', 1003, TO_DATE('2024-05-10', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '의견 감사합니다', NULL, NULL, 'A', 1003, TO_DATE('2024-05-11', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '잘 읽었습니다', NULL, NULL, 'A', 1003, TO_DATE('2024-05-12', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '참 유익한 정보', NULL, NULL, 'A', 1003, TO_DATE('2024-05-13', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '많은 도움이 되었습니다', NULL, NULL, 'A', 1004, TO_DATE('2024-05-14', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '덕분에 많이 배웠습니다', NULL, NULL, 'A', 1005, TO_DATE('2024-05-15', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '정말 감사합니다', NULL, NULL, 'A', 1006, TO_DATE('2024-05-16', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '이해가 잘 되었습니다', NULL, NULL, 'A', 1007, TO_DATE('2024-05-17', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '확인 감사합니다', NULL, NULL, 'A', 1008, TO_DATE('2024-05-18', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '너무 유익했습니다', NULL, NULL, 'A', 1009, TO_DATE('2024-05-19', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '정말 좋네요', NULL, NULL, 'A', 1004, TO_DATE('2024-05-20', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '잘 읽었습니다', NULL, NULL, 'A', 1005, TO_DATE('2024-05-21', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '정말 감사드립니다', NULL, NULL, 'A', 1006, TO_DATE('2024-05-22', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '좋은 정보 공유 감사합니다', NULL, NULL, 'B', 1007, TO_DATE('2024-05-23', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

INSERT INTO TBL_REPLY (
REPLY_NO, REPLY_CONTENT, REF_BNO, UPR_REPLY_NO, STATUS, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
REPLY_NO_SEQ.NEXTVAL, '의견 감사합니다', NULL, NULL, 'B', 1008, TO_DATE('2024-05-24', 'YYYY-MM-DD'), NULL, NULL, 'Y'
);

COMMIT;