-- MODIFY는  예약어 이므로 ""로 감싸야함
-- 직책 정보
INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'PS001', '서버관리자', 1001, 1001, SYSDATE, SYSDATE
);

INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'PS002', '대표', 1002, 1002, SYSDATE, SYSDATE
);

INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'PS003', '이사', 1003, 1003, SYSDATE, SYSDATE
);

INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'PS004', '사원', 1004, 1004, SYSDATE, SYSDATE
);

INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'PS005', '지점장', 1005, 1005, SYSDATE, SYSDATE
);

-- 직급 정보
INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'RK001', '서버관리자', 1001, 1001, SYSDATE, SYSDATE
);

INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'RK002', '대표', 1002, 1002, SYSDATE, SYSDATE
);

INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'RK003', '임원 (이사)', 1003, 1003, SYSDATE, SYSDATE
);

INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'RK004', '사원', 1004, 1004, SYSDATE, SYSDATE
);

INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'RK005', '과장', 1005, 1005, SYSDATE, SYSDATE
);

INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'RK006', '대리', 1006, 1006, SYSDATE, SYSDATE
);

INSERT INTO TBL_COMMON_CODE (
CD, NM, CREATER, "MODIFY", CREATE_DATE, MODIFY_DATE
) VALUES (
'RK007', '주임', 1007, 1007, SYSDATE, SYSDATE
);

COMMIT;