INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '경영지원실', 'HR실', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, 'HR실', '경영지원실', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '회계팀', '재무팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '재무팀', '회계팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '영업지원1팀', '영업지원2팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '영업지원2팀', '영업지원1팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '온라인 마케팅팀', '영업지원1팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '개발팀', '정보보안팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '정보보안팀', '개발팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '영업지원1팀', '온라인 마케팅팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '영업지원2팀', '온라인 마케팅팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '영업지원1팀', '영업지원2팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '영업지원2팀', '영업지원1팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');

INSERT INTO TBL_DEP_TRANSFER (TRANSFER_CODE, TRANSFER_BEFORE, TRANSFER_AFTER, TRANSFER_DATE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (DEPT_TRANSFER_NO_SEQ.NEXTVAL, '개발팀', '정보보안팀', SYSDATE, 1006, SYSDATE, 1003, SYSDATE, 'Y');