INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '경영지원실', 'HR실', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', 'HR실', '경영지원실', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '회계팀', '재무팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '재무팀', '회계팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '영업지원1팀', '영업지원2팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '영업지원2팀', '영업지원1팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '온라인 마케팅팀', '영업지원1팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '개발팀', '정보보안팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '정보보안팀', '개발팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '영업지원1팀', '온라인 마케팅팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '영업지원2팀', '온라인 마케팅팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '경영지원실', 'HR실', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', 'HR실', '경영지원실', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '회계팀', '재무팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '재무팀', '회계팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '영업지원1팀', '영업지원2팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '영업지원2팀', '영업지원1팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '온라인 마케팅팀', '영업지원1팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '개발팀', '정보보안팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '정보보안팀', '개발팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '영업지원1팀', '온라인 마케팅팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '영업지원2팀', '온라인 마케팅팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '경영지원실', 'HR실', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', 'HR실', '경영지원실', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '회계팀', '재무팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '재무팀', '회계팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '영업지원1팀', '영업지원2팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '영업지원2팀', '영업지원1팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '온라인 마케팅팀', '영업지원1팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '개발팀', '정보보안팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '정보보안팀', '개발팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '일정', '영업지원1팀', '온라인 마케팅팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

INSERT INTO TBL_LOG (LOG_NO, LOG_TYPE, MENU_NAME, BEFOR_DATA, AFTER_DATA, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USER_YN, DOCUMENT_NO)
VALUES (LOG_NO_SEQ.NEXTVAL, 1, '공지사항', '영업지원2팀', '온라인 마케팅팀', 1005, SYSDATE, 1005, SYSDATE, 'Y', NULL);

COMMIT;