-- 1. 주문 1
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (

ORDER_NO_SEQ.NEXTVAL, 1010, '핫도그', 'Y', SYSDATE, SYSDATE,

1010, SYSDATE, 'Y'
);
-- 2. 주문 2
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
ORDER_NO_SEQ.NEXTVAL, 1010, '김밥, 컵라면', 'N', SYSDATE, SYSDATE,
1010, SYSDATE, 'Y'
);
-- 3. 주문 3
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
ORDER_NO_SEQ.NEXTVAL, 1010, '아이스크림, 커피', 'Y', SYSDATE, SYSDATE,
1010, SYSDATE, 'Y'
);
-- 4. 주문 4
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
ORDER_NO_SEQ.NEXTVAL, 1010, '과일주스, 삼각김밥', 'N', SYSDATE, SYSDATE,
1010, SYSDATE, 'Y'
);
-- 5. 주문 5
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
ORDER_NO_SEQ.NEXTVAL, 1010, '커스터드빵, 피자', 'Y', SYSDATE, SYSDATE,
1010, SYSDATE, 'Y'
);
-- 6. 주문 6
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
ORDER_NO_SEQ.NEXTVAL, 1010, '떡볶이, 소시지빵', 'Y', SYSDATE, SYSDATE,
1010, SYSDATE, 'Y'
);
-- 7. 주문 7
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
ORDER_NO_SEQ.NEXTVAL, 1010, '핫도그, 피자', 'N', SYSDATE, SYSDATE,
1010, SYSDATE, 'Y'
);
-- 8. 주문 8
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
ORDER_NO_SEQ.NEXTVAL, 1010, '초코파이, 피자', 'Y', SYSDATE, SYSDATE,
1010, SYSDATE, 'Y'
);
-- 9. 주문 9
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
ORDER_NO_SEQ.NEXTVAL, 1010, '컵라면, 삼각김밥', 'Y', SYSDATE, SYSDATE,
1010, SYSDATE, 'Y'
);
-- 10. 주문 10
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
ORDER_NO_SEQ.NEXTVAL, 1010, '맥스, 초코파이', 'N', SYSDATE, SYSDATE,
1010, SYSDATE, 'Y'
);
-- 11. 주문 11
INSERT INTO TBL_ORDERING(
    ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
    MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
    ORDER_NO_SEQ.NEXTVAL, 1010, '초코파이, 커피', 'Y', SYSDATE, SYSDATE,
    1010, SYSDATE, 'Y'
);
-- 12. 주문 12
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
ORDER_NO_SEQ.NEXTVAL, 1010, '라면, 떡볶이', 'N', SYSDATE, SYSDATE,
1010, SYSDATE, 'Y'
);
-- 13. 주문 13
INSERT INTO TBL_ORDERING(
ORDER_NO, EMP_NO, ORDER_PRODUCT, ORDER_STATUS, ORDER_CHECKDATE, CREATE_DATE,
MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
ORDER_NO_SEQ.NEXTVAL, 1010, '피자, 김밥', 'Y', SYSDATE, SYSDATE,
1010, SYSDATE, 'Y'
);

COMMIT;