-- 1. GS25 핫도그
INSERT INTO TBL_PRODUCT (
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 5, '핫도그', 3600, 1200, '50%', 'Y', TO_DATE('2024-12-31', 'YYYY-MM-DD'), 'https://i.ibb.co/yfdxrx7/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 3. GS25 김밥
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 1, '김밥', 1200, 1800, '33.3%', 'Y', TO_DATE('2024-11-30', 'YYYY-MM-DD'), 'https://i.ibb.co/dDRr4vK/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 4. GS25 컵라면
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 1, '컵라면', 500, 800, '60%', 'Y', TO_DATE('2025-03-15', 'YYYY-MM-DD'), 'https://i.ibb.co/1zFDLWP/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 5. GS25 아이스크림
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 5, '아이스크림', 3800, 1200, '50%', 'Y', TO_DATE('2025-06-30', 'YYYY-MM-DD'), 'https://i.ibb.co/Msj3fBt/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 6. GS25 과일주스
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 2, '과일주스', 2300, 1000, '40%', 'Y', TO_DATE('2025-01-10', 'YYYY-MM-DD'), 'https://i.ibb.co/q0BjwL9/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 7. GS25 삼각김밥
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 1, '삼각김밥', 600, 900, '50%', 'Y', TO_DATE('2024-11-10', 'YYYY-MM-DD'), 'https://i.ibb.co/zhgSmxg/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 8. GS25 커피
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 2, '커피', 500, 1000, '50%', 'Y', TO_DATE('2025-02-20', 'YYYY-MM-DD'), 'https://i.ibb.co/xzznF0m/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 9. GS25 초코파이
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 4, '초코파이', 1000, 1500, '33.3%', 'Y', TO_DATE('2025-05-01', 'YYYY-MM-DD'), 'https://i.ibb.co/ThJhpcN/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 11. GS25 라면
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 1, '라면', 700, 1000, '30%', 'Y', TO_DATE('2025-03-31', 'YYYY-MM-DD'), 'https://i.ibb.co/QnkjHxk/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 12. GS25 떡볶이
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 1, '떡볶이', 5400, 1800, '33.3%', 'Y', TO_DATE('2025-02-28', 'YYYY-MM-DD'), 'https://i.ibb.co/9rxf0Wk/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 13. GS25 김치찌개
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 1, '김치찌개', 5000, 3000, '33.3%', 'Y', TO_DATE('2025-01-15', 'YYYY-MM-DD'), 'https://i.ibb.co/6wsCfkd/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 15. GS25 소시지빵
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 4, '소시지빵', 800, 1500, '46.7%', 'Y', TO_DATE('2025-04-30', 'YYYY-MM-DD'), 'https://i.ibb.co/28Nw2cF/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 17. GS25 커스터드빵
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 4, '커스터드빵', 950, 1700, '44.1%', 'Y', TO_DATE('2025-08-15', 'YYYY-MM-DD'), 'https://i.ibb.co/ZLbJYnC/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 18. GS25 피자
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 1,'피자', 4000, 6000, '33.3%', 'Y', TO_DATE('2025-09-10', 'YYYY-MM-DD'), 'https://i.ibb.co/yf9VdXn/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 19. GS25 스파게티
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 1, '스파게티', 2500, 4000, '37.5%', 'Y', TO_DATE('2025-05-25', 'YYYY-MM-DD'), 'https://i.ibb.co/Jjhmqzm/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 술 종류 데이터 (5개)
-- 21. 참이슬 Fresh 360ml
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 3, '참이슬 Fresh 360ml', 1200, 2000, '40%', 'Y', TO_DATE('2025-08-30', 'YYYY-MM-DD'), 'https://i.ibb.co/YbwZycd/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 22. 하이트 진로 500ml
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 3, '하이트 진로 500ml', 1000, 1500, '33.3%', 'Y', TO_DATE('2025-07-15', 'YYYY-MM-DD'), 'https://i.ibb.co/f1Bmcn8/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 23. 맥스 500ml
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 3, '맥스 500ml', 1200, 1800, '33.3%', 'Y', TO_DATE('2025-09-10', 'YYYY-MM-DD'), 'https://i.ibb.co/0ZdHNgt/image.webp',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 24. 롱섬 와인 750ml
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 3, '롱섬 와인 750ml', 3000, 5000, '40%', 'Y', TO_DATE('2025-12-31', 'YYYY-MM-DD'), 'https://i.ibb.co/c37zvDR/image.jpg',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);
-- 25. 발렌타인 12년 700ml
INSERT INTO TBL_PRODUCT(
PRODUCT_NO, CLASSIFICATION_NO, PRODUCT_NAME, COST, SAIL_PRICE, PROFIT_MARGIN, RECOMMENDED_CATEGORY,
EXPIRATION_PERIOD, PRODUCT_IMG, CREATER, CREATE_DATE, MODIFIER, MODIFY_DATE,
DELIVERY_DATE, USE_YN
) VALUES (
PRODUCT_NO_SEQ.NEXTVAL, 3, '발렌타인 12년 700ml', 20000, 30000, '33.3%', 'Y', TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'https://i.ibb.co/8xJVYpY/image.png',
1010, SYSDATE, 1010, SYSDATE, '월화수목금', 'Y'
);

COMMIT;