INSERT INTO TBL_BOARDTYPE (BOARD_TYPE_NO, BOARDT_NAME, BOARDT_TYPE, BOARDT_READ, BOARDT_WRITE, BOARDT_CONTENT, BOARDT_USE, DEPT_CODE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (BOARD_TYPE_NO_SEQ.NEXTVAL, '공지사항게시판', 'N', 5, 5, 3, 'Y', NULL, 1001, SYSDATE, 1001, SYSDATE, 'Y');

INSERT INTO TBL_BOARDTYPE (BOARD_TYPE_NO, BOARDT_NAME, BOARDT_TYPE, BOARDT_READ, BOARDT_WRITE, BOARDT_CONTENT, BOARDT_USE, DEPT_CODE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (BOARD_TYPE_NO_SEQ.NEXTVAL, '자유게시판', 'G', 5, 5, 5, 'Y', NULL, 1001, SYSDATE, 1001, SYSDATE, 'Y');

INSERT INTO TBL_BOARDTYPE (BOARD_TYPE_NO, BOARDT_NAME, BOARDT_TYPE, BOARDT_READ, BOARDT_WRITE, BOARDT_CONTENT, BOARDT_USE, DEPT_CODE, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN)
VALUES (BOARD_TYPE_NO_SEQ.NEXTVAL, '익명게시판', 'S', 5, 5, 5, 'Y', NULL, 1001, SYSDATE, 1001, SYSDATE, 'Y');

COMMIT;