-- 샘플 데이터 1: 최고 관리자 부서 (상위 부서 없음)
INSERT INTO TBL_DEPARTMENT (
DEPT_CODE, DEPT_UPSTAIR, DEPT_NAME, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
'D001', NULL, '경영진', 1001, SYSDATE, 1001, SYSDATE, 'Y'
);
-- 샘플 데이터 2: 경영진 부서의 하위 부서
INSERT INTO TBL_DEPARTMENT (
DEPT_CODE, DEPT_UPSTAIR, DEPT_NAME, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
'D002', 'D001', '인사부', 1002, SYSDATE, 1002, SYSDATE, 'Y'
);
-- 샘플 데이터 3: 경영진 부서의 하위 부서
INSERT INTO TBL_DEPARTMENT (
DEPT_CODE, DEPT_UPSTAIR, DEPT_NAME, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
'D003', 'D001', '재무부', 1003, SYSDATE, 1003, SYSDATE, 'Y'
);
-- 샘플 데이터 4: 인사부의 하위 부서
INSERT INTO TBL_DEPARTMENT (
DEPT_CODE, DEPT_UPSTAIR, DEPT_NAME, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
'D004', 'D002', '채용팀', 1004, SYSDATE, 1004, SYSDATE, 'Y'
);
-- 샘플 데이터 5: 재무부의 하위 부서
INSERT INTO TBL_DEPARTMENT (
DEPT_CODE, DEPT_UPSTAIR, DEPT_NAME, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
'D005', 'D003', '회계팀', 1005, SYSDATE, 1005, SYSDATE, 'Y'
);
-- 샘플 데이터 6: 경영진 부서의 하위 부서
INSERT INTO TBL_DEPARTMENT (
DEPT_CODE, DEPT_UPSTAIR, DEPT_NAME, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
'D006', 'D001', '영업부', 1006, SYSDATE, 1006, SYSDATE, 'Y'
);
-- 샘플 데이터 7: 영업부의 하위 부서
INSERT INTO TBL_DEPARTMENT (
DEPT_CODE, DEPT_UPSTAIR, DEPT_NAME, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
'D007', 'D006', '서울지사', 1007, SYSDATE, 1007, SYSDATE, 'Y'
);
-- 샘플 데이터 8: 서울지사의 하위 부서
INSERT INTO TBL_DEPARTMENT (
DEPT_CODE, DEPT_UPSTAIR, DEPT_NAME, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
'D008', 'D007', '영업1팀', 1008, SYSDATE, 1008, SYSDATE, 'Y'
);
-- 샘플 데이터 9: 경영진 부서의 하위 부서
INSERT INTO TBL_DEPARTMENT (
DEPT_CODE, DEPT_UPSTAIR, DEPT_NAME, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
'D009', 'D001', 'IT부서', 1009, SYSDATE, 1009, SYSDATE, 'Y'
);
-- 샘플 데이터 10: IT부서의 하위 부서
INSERT INTO TBL_DEPARTMENT (
DEPT_CODE, DEPT_UPSTAIR, DEPT_NAME, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN
) VALUES (
'D010', 'D009', '개발팀', 1010, SYSDATE, 1010, SYSDATE, 'Y'
);

COMMIT;