-- 1. 발주 내역 1
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1001, 100, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'N'
);
-- 2. 발주 내역 2
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1002, 200, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'Y'
);
-- 3. 발주 내역 3
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1003, 150, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'N'
);
-- 4. 발주 내역 4
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1004, 250, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'Y'
);
-- 5. 발주 내역 5
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1005, 180, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'N'
);
-- 6. 발주 내역 6
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1006, 300, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'Y'
);
-- 7. 발주 내역 7
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1007, 120, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'N'
);
-- 8. 발주 내역 8
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1008, 50, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'Y'
);
-- 9. 발주 내역 9
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1009, 75, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'N'
);
-- 10. 발주 내역 10
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1010, 220, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'Y'
);
-- 11. 발주 내역 11
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1011, 80, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'N'
);
-- 12. 발주 내역 12
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1012, 170, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'Y'
);
-- 13. 발주 내역 13
INSERT INTO TBL_ORDERING_PRODUCT(
PRODUCT_NO, ORDER_COUNT, EMP_NO, CREATE_DATE, MODIFIER, MODIFY_DATE, USE_YN, EVENT
) VALUES (
1013, 250, 1010, SYSDATE, 1010, SYSDATE, 'Y', 'N'
);

COMMIT;